<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e3bd775a-609e-4b97-b138-f983d6f3a3c8</testSuiteGuid>
   <testCaseLink>
      <guid>633b3776-095f-452b-a824-b2d60fbb05bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aimweb/a. Login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4419250e-e225-4045-88a0-81d35a2e19f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aimweb/b. Home Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>839ee5b2-9943-4fe9-a836-9b9412b2538f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7dd05ab-140f-4fe3-9d63-3a3b220c7f99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aimweb/c. Create Quote New</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>877d2a1f-e701-4633-b44e-a49f6813ac4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71ccaed1-766f-4511-ad6f-d98cae449c16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c68af7a-d718-4c22-835b-82c824890c11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13a33134-0d10-4212-9a9a-3fc949d5aa87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ead962b2-372c-4e5e-bf9d-265e97b53930</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ce9b2dd-27bf-4bdb-bf45-ac3d164034a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>041f4531-85c3-4b21-9dde-915a3f1996c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43898f91-b548-4c1f-af01-34d39b27fc57</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>191727a4-41ef-4fbf-b511-7c39378cf600</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aimweb/d. Lock Quote</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e5c6dab6-7c25-4809-b15a-b689febce904</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Aimweb/e. Close</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
